name: Deploy to Cloud Run

on:
    push:
        paths:
            - "src/**"
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: "read"
            id-token: "write"

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Google Auth
              uses: "google-github-actions/auth@v1"
              with:
                  credentials_json: "${{ secrets.GCLOUD_SERVICE_KEY }}"

            - name: Set up Cloud SDK
              uses: "google-github-actions/setup-gcloud@v1"

            - name: Create Service Account Key File
              run: |
                  cd src/config
                  echo '${{ secrets.KEY_STORAGE_FIRESTORE }}' > key.json

            - name: Authenticate Docker with GCP
              run: gcloud auth configure-docker

            - name: Build and Push Docker Image
              run: |
                  IMAGE_NAME="gcr.io/${{ secrets.GCLOUD_PROJECT_ID}}/cc-service"
                  docker build -t $IMAGE_NAME .
                  docker push $IMAGE_NAME

            - name: Deploy to Cloud Run
              run: |
                  gcloud run deploy cc-service \
                    --image=gcr.io/${{ secrets.GCLOUD_PROJECT_ID}}/cc-service \
                    --region=${{ secrets.GCLOUD_REGION }} \
                    --platform=managed \
                    --allow-unauthenticated 
                 
